#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) unless $:.include?(lib_path)
require 'backmeup/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Backmeup::CLI.start
rescue Backmeup::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
